package devel.semantic_analysis;

import core.abstract_syntax.syntaxtree.And;
import core.abstract_syntax.syntaxtree.ArrayAssign;
import core.abstract_syntax.syntaxtree.ArrayLength;
import core.abstract_syntax.syntaxtree.ArrayLookup;
import core.abstract_syntax.syntaxtree.Assign;
import core.abstract_syntax.syntaxtree.Block;
import core.abstract_syntax.syntaxtree.BooleanType;
import core.abstract_syntax.syntaxtree.Call;
import core.abstract_syntax.syntaxtree.ClassDeclExtends;
import core.abstract_syntax.syntaxtree.ClassDeclSimple;
import core.abstract_syntax.syntaxtree.False;
import core.abstract_syntax.syntaxtree.Formal;
import core.abstract_syntax.syntaxtree.Identifier;
import core.abstract_syntax.syntaxtree.IdentifierExp;
import core.abstract_syntax.syntaxtree.IdentifierType;
import core.abstract_syntax.syntaxtree.If;
import core.abstract_syntax.syntaxtree.IntArrayType;
import core.abstract_syntax.syntaxtree.IntegerLiteral;
import core.abstract_syntax.syntaxtree.IntegerType;
import core.abstract_syntax.syntaxtree.LessThan;
import core.abstract_syntax.syntaxtree.MainClass;
import core.abstract_syntax.syntaxtree.MethodDecl;
import core.abstract_syntax.syntaxtree.Minus;
import core.abstract_syntax.syntaxtree.NewArray;
import core.abstract_syntax.syntaxtree.NewObject;
import core.abstract_syntax.syntaxtree.Not;
import core.abstract_syntax.syntaxtree.Plus;
import core.abstract_syntax.syntaxtree.Print;
import core.abstract_syntax.syntaxtree.Program;
import core.abstract_syntax.syntaxtree.This;
import core.abstract_syntax.syntaxtree.Times;
import core.abstract_syntax.syntaxtree.True;
import core.abstract_syntax.syntaxtree.Type;
import core.abstract_syntax.syntaxtree.VarDecl;
import core.abstract_syntax.syntaxtree.While;

public interface SecondPhaseTypeCheckVisitor {
//	public Type visit(Program n);
	public Type visit(MainClass n);
//	public Type visit(ClassDeclSimple n);
//	public Type visit(ClassDeclExtends n);
//	public Type visit(VarDecl n);
//	public Type visit(MethodDecl n);
//	public Type visit(Formal n);
	public Type visit(IntArrayType n);
	public Type visit(BooleanType n);
	public Type visit(IntegerType n);
	public Type visit(IdentifierType n);
	public Type visit(Block n);
	public Type visit(If n);
	public Type visit(While n);
	public Type visit(Print n);
	public Type visit(Assign n);
	public Type visit(ArrayAssign n);
	public Type visit(And n);
	public Type visit(LessThan n);
	public Type visit(Plus n);
	public Type visit(Minus n);
	public Type visit(Times n);
	public Type visit(ArrayLookup n);
	public Type visit(ArrayLength n);
	public Type visit(IntegerLiteral n);
	public Type visit(Call n);
	public Type visit(True n);
	public Type visit(False n);
	public Type visit(IdentifierExp n);
	public Type visit(This n);
	public Type visit(NewArray n);
	public Type visit(NewObject n);
	public Type visit(Not n);
public Type visit(Identifier n);


}
